// Preload audio elements
const shuffleSound = new Audio('shuffle.mp3');
const beepSound = new Audio('beep.mp3');

// Movies Database
const movieData = {
  romcom: [
    { title: "Jab We Met", desc: "A depressed businessman finds a new lease on life after meeting a free-spirited Punjabi girl on a train.", rating: "7.9 ⭐", watch: "Netflix / JioCinema" },
    { title: "When Harry Met Sally...", desc: "Two friends navigate a love-hate relationship over 12 years, asking if men and women can ever just be friends.", rating: "7.7 ⭐", watch: "Amazon Prime Video" },
    { title: "Yeh Jawaani Hai Deewani", desc: "Kabir and Naina discover themselves and fall in love during a college trekking trip to Manali.", rating: "7.2 ⭐", watch: "Netflix" },
    { title: "10 Things I Hate About You", desc: "A high school boy attempts to pay a bad boy to date a shrewish girl so he can date her younger sister.", rating: "7.3 ⭐", watch: "Disney+ Hotstar" },
    { title: "Crazy Rich Asians", desc: "An Asian-American professor travels to Singapore to meet her boyfriend's family, discovering they are insanely wealthy.", rating: "6.9 ⭐", watch: "Amazon Prime Video" },
    { title: "Bareilly Ki Barfi", desc: "A free-spirited girl falls in love with the author of a book, leading to a hilarious love triangle.", rating: "7.5 ⭐", watch: "Netflix" },
    { title: "The Proposal", desc: "A pushy boss forces her young assistant to marry her in order to keep her visa status in the US.", rating: "6.7 ⭐", watch: "Disney+ Hotstar" },
    { title: "Jaane Tu... Ya Jaane Na", desc: "Two best friends are convinced they are not in love, so they search for their ideal partners.", rating: "7.5 ⭐", watch: "Netflix" },
    { title: "500 Days of Summer", desc: "An hopeless romantic hopeless reflects on his 500-day relationship with a woman who doesn't believe in love.", rating: "7.7 ⭐", watch: "Disney+ Hotstar" },
    { title: "Hasee Toh Phasee", desc: "Nikhil meets Meeta, an eccentric scientist, just days before marrying her conventional sister.", rating: "6.8 ⭐", watch: "Netflix" },
    { title: "To All the Boys I've Loved Before", desc: "A teenage girl's secret love letters are accidentally mailed to all of her crushes.", rating: "7.0 ⭐", watch: "Netflix" },
    { title: "Band Baaja Baaraat", desc: "Two ambitious Delhi graduates team up as wedding planners, swearing never to let romance ruin their business.", rating: "7.2 ⭐", watch: "Amazon Prime Video" },
    { title: "About Time", desc: "A young man with the ability to time travel tries to change his past to improve his romantic future.", rating: "7.8 ⭐", watch: "Netflix" },
    { title: "Cocktail", desc: "A love triangle emerges when a wild girl, a quiet girl, and a charming guy share a London apartment.", rating: "6.3 ⭐", watch: "JioCinema" },
    { title: "Notting Hill", desc: "The life of a simple bookshop owner changes when he meets the most famous film star in the world.", rating: "7.2 ⭐", watch: "Amazon Prime Video" },
    { title: "Socha Na Tha", desc: "Two young people forced into an arranged meeting refuse the match, only to fall for each other later.", rating: "7.4 ⭐", watch: "JioCinema" },
    { title: "Crazy, Stupid, Love.", desc: "A middle-aged man receives dating advice from a smooth-talking bachelor after his wife asks for a divorce.", rating: "7.4 ⭐", watch: "Amazon Prime Video" },
    { title: "Sonu Ke Titu Ki Sweety", desc: "A protective best friend attempts to save his naive pal from marrying a woman he suspects is a gold digger.", rating: "7.1 ⭐", watch: "Amazon Prime Video" },
    { title: "Set It Up", desc: "Two overworked assistants trick their workaholic bosses into falling in love with each other.", rating: "6.5 ⭐", watch: "Netflix" },
    { title: "Hum Tum", desc: "A cartoonist and a fashion designer keep crossing paths over the years through fate and coincidence.", rating: "7.0 ⭐", watch: "Amazon Prime Video" },
    { title: "Clueless", desc: "A wealthy high school student fancies herself a matchmaker while navigating teenage social circles.", rating: "6.9 ⭐", watch: "Netflix" },
    { title: "Badrinath Ki Dulhania", desc: "An ambitious girl fights for her independence when a wealthy lover from a traditional family tries to court her.", rating: "6.1 ⭐", watch: "Amazon Prime Video" },
    { title: "Palm Springs", desc: "Two wedding guests get stuck in a surreal time loop and bond while living the same day over and over.", rating: "7.4 ⭐", watch: "Amazon Prime Video" },
    { title: "Love Aaj Kal", desc: "Two modern lovers break up to pursue their careers, parallelled by an old-fashioned love story from the past.", rating: "6.8 ⭐", watch: "JioCinema" },
    { title: "Pretty Woman", desc: "A wealthy businessman hires an enchanting escort to accompany him to social events, leading to unexpected love.", rating: "7.1 ⭐", watch: "Disney+ Hotstar" },
    { title: "Tanu Weds Manu", desc: "An NRI doctor falls in love with a fiery, rebellious girl who has no interest in marrying him.", rating: "7.0 ⭐", watch: "Netflix" },
    { title: "How to Lose a Guy in 10 Days", desc: "A magazine columnist and an ad executive start a relationship with conflicting secret bets.", rating: "6.5 ⭐", watch: "Amazon Prime Video" },
    { title: "2 States", desc: "A couple from two very different Indian cultural backgrounds struggle to convince their parents to approve their marriage.", rating: "6.9 ⭐", watch: "Disney+ Hotstar" },
    { title: "Love Actually", desc: "Follows the lives of eight very different couples dealing with love during a frantic month before Christmas.", rating: "7.6 ⭐", watch: "Amazon Prime Video" },
    { title: "Ajab Prem Ki Ghazab Kahani", desc: "A happy-go-lucky guy helps the girl he secretly loves run away with her boyfriend.", rating: "6.4 ⭐", watch: "Netflix" },
    { title: "Always Be My Maybe", desc: "Childhood sweethearts reconnect 15 years later, navigating their vastly different adult lives.", rating: "6.8 ⭐", watch: "Netflix" },
    { title: "Shuddh Desi Romance", desc: "Three young people explore non-traditional romance, living together, and fear of commitment.", rating: "5.8 ⭐", watch: "Amazon Prime Video" },
    { title: "13 Going on 30", desc: "A 13-year-old girl makes a wish on her birthday and wakes up as a 30-year-old fashion magazine editor.", rating: "6.3 ⭐", watch: "Netflix" },
    { title: "Namastey London", desc: "A British-born Indian girl is tricked into marrying a rural Punjabi man by her traditional father.", rating: "7.1 ⭐", watch: "Amazon Prime Video" },
    { title: "She's the Man", desc: "A teenage girl disguises herself as her twin brother to play on a boys' soccer team at a rival school.", rating: "6.4 ⭐", watch: "Amazon Prime Video" },
    { title: "Kal Ho Naa Ho", desc: "An extroverted, terminally ill man acts as a matchmaker to help the gloomy girl he secretly loves.", rating: "7.9 ⭐", watch: "Amazon Prime Video" },
    { title: "My Best Friend's Wedding", desc: "When a woman's long-time friend reveals he's getting married, she realizes she wants him for herself.", rating: "6.3 ⭐", watch: "Netflix" },
    { title: "Piku", desc: "A quirky comedy about the relationship between an aging hypochondriac father and his independent architect daughter.", rating: "7.6 ⭐", watch: "SonyLIV" },
    { title: "Silver Linings Playbook", desc: "A man with bipolar disorder meets a young widow who offers to help him win back his wife if he enters a dance competition.", rating: "7.7 ⭐", watch: "Amazon Prime Video" },
    { title: "Khosla Ka Ghosla!", desc: "A middle-class family attempts an elaborate scam to retrieve their stolen land from a corrupt builder.", rating: "8.3 ⭐", watch: "Disney+ Hotstar" },
    { title: "The Holiday", desc: "Two women troubled with guy problems swap homes in different countries for Christmas, finding romance.", rating: "6.9 ⭐", watch: "Netflix" },
    { title: "Chup Chup Ke", desc: "A debt-ridden man pretends to be deaf and mute, ending up as household help in a wealthy family.", rating: "7.0 ⭐", watch: "Netflix" },
    { title: "Bridget Jones's Diary", desc: "A British woman keeps a personal diary detailing her struggles with weight, career, and two suitors.", rating: "6.8 ⭐", watch: "Amazon Prime Video" },
    { title: "Dolly Ki Doli", desc: "A clever con woman marries wealthy grooms only to drug their family on the wedding night and loot them.", rating: "5.3 ⭐", watch: "Disney+ Hotstar" },
    { title: "You've Got Mail", desc: "Two business rivals fall in love online, unaware of each other's true real-life identity.", rating: "6.7 ⭐", watch: "Amazon Prime Video" },
    { title: "Main Tera Hero", desc: "A rebellious young man falls in love with a girl who is being forced to marry a corrupt cop.", rating: "5.1 ⭐", watch: "Disney+ Hotstar" },
    { title: "Sleeping With Other People", desc: "A good-natured womanizer and a serial cheater form a platonic friendship that gradually turns romantic.", rating: "6.5 ⭐", watch: "Amazon Prime Video" },
    { title: "Vicky Donor", desc: "A young man becomes a sperm donor for a fertility doctor, keeping his lucrative job a secret from his new bride.", rating: "7.8 ⭐", watch: "Eros Now" },
    { title: "Warm Bodies", desc: "After a highly unusual zombie saves a still-living girl, their growing relationship sets off events that transform the world.", rating: "6.7 ⭐", watch: "Amazon Prime Video" },
    { title: "Badhaai Ho", desc: "A 25-year-old middle-class man faces extreme social embarrassment when his middle-aged mother gets pregnant.", rating: "7.9 ⭐", watch: "Disney+ Hotstar" }
  ],

  crime: [
    { title: "Andhadhun", desc: "A blind pianist gets unwittingly entangled in a series of mysterious events after witnessing a murder.", rating: "8.2 ⭐", watch: "Netflix" },
    { title: "The Godfather", desc: "The patriarch of an organized crime dynasty transfers control of his empire to his reluctant son.", rating: "9.2 ⭐", watch: "Amazon Prime Video" },
    { title: "Kahaani", desc: "A pregnant woman searches for her missing husband in Kolkata during the Durga Puja festival.", rating: "8.1 ⭐", watch: "JioCinema" },
    { title: "Pulp Fiction", desc: "The lives of mob hitmen, a boxer, and a gangster's wife intertwine in four tales of violence.", rating: "8.9 ⭐", watch: "Amazon Prime Video" },
    { title: "Drishyam", desc: "A cable operator goes to extreme lengths to protect his family after an accidental crime.", rating: "8.2 ⭐", watch: "Disney+ Hotstar" },
    { title: "Goodfellas", desc: "The story of Henry Hill and his life in the mob, covering his relationship with his wife and partners.", rating: "8.7 ⭐", watch: "Amazon Prime Video" },
    { title: "Se7en", desc: "Two detectives hunt a serial killer who uses the seven deadly sins as his motives.", rating: "8.6 ⭐", watch: "Amazon Prime Video" },
    { title: "Gangs of Wasseypur", desc: "A multi-generational blood feud between coal lords and gangsters in Dhanbad, Jharkhand.", rating: "8.2 ⭐", watch: "Netflix" },
    { title: "The Departed", desc: "An undercover cop and a mole in the police force attempt to identify each other.", rating: "8.5 ⭐", watch: "Amazon Prime Video" },
    { title: "Sacred Games", desc: "A troubled police officer receives a phone call from a notorious criminal overlord warning of a nuclear threat.", rating: "8.5 ⭐", watch: "Netflix" },
    { title: "The Silence of the Lambs", desc: "A young FBI cadet must receive the help of a cannibalistic murderer to catch another killer.", rating: "8.6 ⭐", watch: "Amazon Prime Video" },
    { title: "Special 26", desc: "A team of conmen pose as CBI officers to execute raids on politicians and businessmen.", rating: "8.0 ⭐", watch: "JioCinema" },
    { title: "The Usual Suspects", desc: "A sole survivor tells the twisting events leading to a horrific gun battle on a boat.", rating: "8.5 ⭐", watch: "Amazon Prime Video" },
    { title: "Talvar", desc: "An experienced investigator investigates the conflicting theories surrounding a double murder case.", rating: "8.1 ⭐", watch: "Disney+ Hotstar" },
    { title: "City of God", desc: "Two boys growing up in a violent neighborhood of Rio de Janeiro take different paths.", rating: "8.6 ⭐", watch: "Amazon Prime Video" },
    { title: "Badlapur", desc: "A man seeks relentless vengeance on the two bank robbers who killed his wife and son.", rating: "7.4 ⭐", watch: "Eros Now" },
    { title: "Reservoir Dogs", desc: "When a simple jewelry heist goes terribly wrong, the surviving criminals suspect a police informant.", rating: "8.3 ⭐", watch: "Amazon Prime Video" },
    { title: "Raman Raghav 2.0", desc: "A serial killer obsessed with a 1960s murderer finds a soulmate in a corrupt drug-addicted cop.", rating: "7.3 ⭐", watch: "ZEE5" },
    { title: "Heat", desc: "A group of high-end professional bank robbers feel the heat from the LAPD when they leave a clue.", rating: "8.3 ⭐", watch: "Amazon Prime Video" },
    { title: "Article 15", desc: "An upright police officer investigates the disappearance of three young girls from a small village.", rating: "8.1 ⭐", watch: "Netflix" },
    { title: "Scarface", desc: "A Cuban immigrant arrives in Miami with nothing and rises to become a powerful drug kingpin.", rating: "8.3 ⭐", watch: "Netflix" },
    { title: "Shootout at Lokhandwala", desc: "A massive force of 400 policemen lay siege to a residential building housing five ruthless gangsters.", rating: "7.1 ⭐", watch: "Disney+ Hotstar" },
    { title: "Snatch", desc: "Unscrupulous boxing promoters, violent bookmakers, and Russian gangsters hunt for a stolen diamond.", rating: "8.2 ⭐", watch: "Amazon Prime Video" },
    { title: "Once Upon a Time in Mumbaai", desc: "The rise of a smuggler in 1970s Mumbai and his eventual clash with his ambitious protégé.", rating: "7.4 ⭐", watch: "Balaji" },
    { title: "L.A. Confidential", desc: "Three LAPD officers investigate a series of murders with their own brand of justice in 1950s Los Angeles.", rating: "8.2 ⭐", watch: "Amazon Prime Video" },
    { title: "Raees", desc: "A clever bootlegger builds an empire in Gujarat while trying to outsmart a tough police officer.", rating: "6.8 ⭐", watch: "Netflix" },
    { title: "Zodiac", desc: "A cartoonist becomes obsessed with tracking down the Zodiac Killer in late 1960s San Francisco.", rating: "7.7 ⭐", watch: "Amazon Prime Video" },
    { title: "Gully Boy", desc: "A street rapper from the slums of Mumbai uses music to break free from his poverty and family drama.", rating: "7.9 ⭐", watch: "Amazon Prime Video" },
    { title: "Casino", desc: "A tale of greed, deception, power, and murder between two best friends in Las Vegas.", rating: "8.2 ⭐", watch: "Amazon Prime Video" },
    { title: "Gulaal", desc: "A law student gets dragged into a dirty world of student politics and crime in Rajasthan.", rating: "8.0 ⭐", watch: "YouTube" },
    { title: "No Country for Old Men", desc: "A hunter stumbles upon a drug deal gone wrong and $2 million in cash, pursued by a psychopathic killer.", rating: "8.2 ⭐", watch: "Amazon Prime Video" },
    { title: "Shaitan", desc: "Five rebellious youths fake a kidnapping to pay a bribe, but the plan spirals wildly out of control.", rating: "7.1 ⭐", watch: "Netflix" },
    { title: "Primal Fear", desc: "A high-profile defense attorney takes the case of a young altar boy accused of murdering an archbishop.", rating: "7.7 ⭐", watch: "Amazon Prime Video" },
    { title: "Black Friday", desc: "An in-depth investigation into the events leading up to the 1993 Bombay bomb blasts.", rating: "8.4 ⭐", watch: "Disney+ Hotstar" },
    { title: "Nightcrawler", desc: "A desperate man enters the world of L.A. crime journalism, blurring the line between observer and participant.", rating: "7.8 ⭐", watch: "Amazon Prime Video" },
    { title: "Dev.D", desc: "A modern, gritty retelling of Devdas set against the backdrop of prostitution and drug abuse.", rating: "7.9 ⭐", watch: "Netflix" },
    { title: "Prisoners", desc: "When his young daughter is abducted, a desperate father takes matters into his own hands.", rating: "8.1 ⭐", watch: "Amazon Prime Video" },
    { title: "Company", desc: "A young henchman forms a partnership with a mafia boss, but a rift causes a bloody gang war.", rating: "8.0 ⭐", watch: "ZEE5" },
    { title: "Memories of Murder", desc: "Two detectives struggle to solve Korea's first registered serial murders in a small rural province.", rating: "8.1 ⭐", watch: "Amazon Prime Video" },
    { title: "Omkara", desc: "A political enforcer's misguided trust in his lieutenant leads to tragedy in the underworld of UP.", rating: "8.0 ⭐", watch: "JioCinema" },
    { title: "Sicario", desc: "An idealistic FBI agent is enlisted by a government task force to bring down a brutal Mexican drug cartel.", rating: "7.7 ⭐", watch: "Amazon Prime Video" },
    { title: "Drishyam 2", desc: "7 years after the case was closed, a police investigation threatens to uncover the truth behind the murder.", rating: "8.4 ⭐", watch: "Amazon Prime Video" },
    { title: "The Irishman", desc: "An aging hitman recalls his involvement in the disappearance of labor union leader Jimmy Hoffa.", rating: "7.8 ⭐", watch: "Netflix" },
    { title: "Khakee", desc: "A team of police officers escort a dangerous terrorist across Maharashtra while facing deadly ambushes.", rating: "7.4 ⭐", watch: "Amazon Prime Video" },
    { title: "American Gangster", desc: "An honest detective works to bring down the heroin empire of Frank Lucas in 1970s Harlem.", rating: "7.8 ⭐", watch: "Netflix" },
    { title: "Section 375", desc: "A high-profile film director is accused of rape by a female crew member, sparking a complex legal duel.", rating: "7.7 ⭐", watch: "Amazon Prime Video" },
    { title: "Fargo", desc: "A desperate car salesman hires two criminals to kidnap his wife so he can extract a ransom from his father-in-law.", rating: "8.1 ⭐", watch: "Amazon Prime Video" },
    { title: "Agneepath", desc: "A young boy's father is lynched by a village villain, sparking a lifelong quest for vengeance.", rating: "6.9 ⭐", watch: "Netflix" },
    { title: "Training Day", desc: "A rookie cop spends his first day on the job with a rogue narcotics officer who pushes ethical boundaries.", rating: "7.7 ⭐", watch: "Amazon Prime Video" },
    { title: "D-Day", desc: "A team of undercover Indian agents are sent to Pakistan to bring back Most Wanted criminal Goldman.", rating: "7.2 ⭐", watch: "SonyLIV" }
  ],

  action: [
    { title: "Mad Max: Fury Road", desc: "In a wasteland, a woman rebels against a tyrannical ruler with the help of a quiet wanderer.", rating: "8.1 ⭐", watch: "Amazon Prime Video" },
    { title: "The Dark Knight", desc: "Batman faces his greatest psychological test when a psychotic mastermind named the Joker emerges.", rating: "9.0 ⭐", watch: "JioCinema" },
    { title: "RRR", desc: "A fearless tribal revolutionary and an officer in British India join forces in a heroic quest.", rating: "7.8 ⭐", watch: "Netflix" },
    { title: "John Wick", desc: "An ex-hitman comes out of retirement to hunt down the mobsters who destroyed everything he had left.", rating: "7.4 ⭐", watch: "Lionsgate Play" },
    { title: "Die Hard", desc: "An NYPD officer tries to save his estranged wife and several others taken hostage by terrorists in a skyscraper.", rating: "8.2 ⭐", watch: "Disney+ Hotstar" },
    { title: "Sholay", desc: "Two ex-convicts are hired by a retired police officer to capture a ruthless bandit named Gabbar Singh.", rating: "8.1 ⭐", watch: "Amazon Prime Video" },
    { title: "Gladiator", desc: "A former Roman general sets out to exact vengeance against the corrupt emperor who murdered his family.", rating: "8.5 ⭐", watch: "Amazon Prime Video" },
    { title: "War", desc: "An Indian soldier is tasked with hunting down his former mentor, a rogue secret agent.", rating: "6.5 ⭐", watch: "Amazon Prime Video" },
    { title: "Terminator 2: Judgment Day", desc: "A cyborg is sent from the future to protect a young boy from an advanced shape-shifting assassin.", rating: "8.6 ⭐", watch: "Amazon Prime Video" },
    { title: "Pathaan", desc: "An exiled RAW agent steps up to fight a mercenary leader planning a devastating biological attack.", rating: "5.9 ⭐", watch: "Amazon Prime Video" },
    { title: "Aliens", desc: "Ellen Ripley returns to the moon where her crew encountered the Alien, this time accompanied by space marines.", rating: "8.4 ⭐", watch: "Disney+ Hotstar" },
    { title: "Jawan", desc: "A vigilante commander executes high-stakes hijackings to fix societal corruption in India.", rating: "7.0 ⭐", watch: "Netflix" },
    { title: "The Matrix", desc: "A computer hacker learns from mysterious rebels about the true nature of his reality.", rating: "8.7 ⭐", watch: "JioCinema" },
    { title: "K.G.F: Chapter 1", desc: "A high-ranking assassin disguises himself as a slave laborer to assassinate the owner of the Kolar Gold Fields.", rating: "8.2 ⭐", watch: "Amazon Prime Video" },
    { title: "Top Gun: Maverick", desc: "After thirty years, Maverick trains a detachment of naval aviators for a dangerous specialized mission.", rating: "8.3 ⭐", watch: "Amazon Prime Video" },
    { title: "K.G.F: Chapter 2", desc: "Rocky takes control of the Kolar Gold Fields, while fighting off government forces and rivals.", rating: "8.3 ⭐", watch: "Amazon Prime Video" },
    { title: "Spider-Man: Into the Spider-Verse", desc: "Teen Miles Morales becomes the new Spider-Man and joins five alternate counterparts to stop a multiversal threat.", rating: "8.4 ⭐", watch: "SonyLIV" },
    { title: "Dhoom 2", desc: "A fearless thief steals priceless artifacts across the globe while a sharp police officer pursues him.", rating: "6.6 ⭐", watch: "Amazon Prime Video" },
    { title: "Casino Royale", desc: "James Bond sets out on his first mission as a 00 Agent, attempting to bankrupt a terrorist financier in poker.", rating: "8.0 ⭐", watch: "Amazon Prime Video" },
    { title: "Vikram", desc: "A special black-ops squad investigates a masked vigilante group executing drug kingpins.", rating: "8.3 ⭐", watch: "Disney+ Hotstar" },
    { title: "Logan", desc: "In a future where mutants are nearly extinct, an aging Wolverine protects a young mutant girl.", rating: "8.1 ⭐", watch: "Disney+ Hotstar" },
    { title: "Don 2", desc: "Having conquered the Asian underworld, Don sets his sights on dominating the European drug cartel.", rating: "7.1 ⭐", watch: "Netflix" },
    { title: "Kill Bill: Vol. 1", desc: "After waking from a four-year coma, a former assassin seeks revenge on the team that betrayed her.", rating: "8.2 ⭐", watch: "Amazon Prime Video" },
    { title: "Singham", desc: "An honest police officer stands up against a corrupt politician who dominates a coastal town.", rating: "6.8 ⭐", watch: "JioCinema" },
    { title: "Avengers: Endgame", desc: "The remaining Avengers assemble once more to reverse Thanos's actions and restore balance.", rating: "8.4 ⭐", watch: "Disney+ Hotstar" },
    { title: "Uri: The Surgical Strike", desc: "Indian army special forces execute a covert operation to avenge a terrorist attack on an army base.", rating: "8.2 ⭐", watch: "ZEE5" },
    { title: "Mission: Impossible - Fallout", desc: "Ethan Hunt and his IMF team race against time after a nuclear arms deal goes wrong.", rating: "7.7 ⭐", watch: "Amazon Prime Video" },
    { title: "Ghayal", desc: "An amateur boxer is framed for his brother's murder and takes on a ruthless industrialist.", rating: "7.7 ⭐", watch: "ZEE5" },
    { title: "Speed", desc: "A young SWAT officer must prevent a bomb from exploding aboard a city bus by keeping its speed above 50 mph.", rating: "7.3 ⭐", watch: "Disney+ Hotstar" },
    { title: "Bang Bang!", desc: "A quiet bank receptionist gets swept into a globe-trotting adventure with a mysterious secret agent.", rating: "5.6 ⭐", watch: "Disney+ Hotstar" },
    { title: "The Raid: Redemption", desc: "A SWAT team becomes trapped in a tenement block run by a ruthless mobster and his army of killers.", rating: "7.6 ⭐", watch: "Amazon Prime Video" },
    { title: "Force", desc: "A dedicated narcotics officer wages war against a vengeful drug lord who targets his team.", rating: "6.4 ⭐", watch: "Disney+ Hotstar" },
    { title: "Baby Driver", desc: "A talented getaway driver relies on his personal soundtrack to be the best, coerced into a doomed heist.", rating: "7.6 ⭐", watch: "Amazon Prime Video" },
    { title: "Kanthaswamy", desc: "A superhero vigilante disguised as a rooster grants wishes to the poor by looting corrupt millionaires.", rating: "6.1 ⭐", watch: "YouTube" },
    { title: "Bourne Ultimatum", desc: "Jason Bourne dodges a ruthless CIA official while searching for the origins of his assassin training.", rating: "8.0 ⭐", watch: "Amazon Prime Video" },
    { title: "Guns & Gulaabs", desc: "Mechanics, cartel lords, and an honest officer clash in a 1990s small town filled with opium deals.", rating: "7.7 ⭐", watch: "Netflix" },
    { title: "Skyfall", desc: "James Bond's loyalty to M is tested when her past comes back to haunt her in a devastating attack.", rating: "7.8 ⭐", watch: "Amazon Prime Video" },
    { title: "Baaghi", desc: "A martial arts expert battles a brutal martial arts champion in Bangkok to save his true love.", rating: "5.3 ⭐", watch: "SonyLIV" },
    { title: "Ip Man", desc: "During the Japanese invasion of China, a grandmaster of Wing Chun is forced to fight for survival.", rating: "8.0 ⭐", watch: "Amazon Prime Video" },
    { title: "Commando: A One Man Army", desc: "A trained Indian special forces officer escapes a Chinese prison and protects a woman fleeing a dogmatic thug.", rating: "6.2 ⭐", watch: "ZEE5" },
    { title: "Edge of Tomorrow", desc: "A soldier fighting aliens gets caught in a time loop, reliving the same battle day after day.", rating: "7.9 ⭐", watch: "Amazon Prime Video" },
    { title: "Ra.One", desc: "A game developer creates a virtual reality villain that escapes into the real world.", rating: "4.8 ⭐", watch: "Eros Now" },
    { title: "Guardians of the Galaxy", desc: "A group of intergalactic misfits band together to stop a fanatical warrior from destroying the universe.", rating: "8.0 ⭐", watch: "Disney+ Hotstar" },
    { title: "Main Hoon Na", desc: "An army major goes undercover as a college student to protect a general's daughter from a rogue officer.", rating: "7.0 ⭐", watch: "Netflix" },
    { title: "First Blood", desc: "A troubled Vietnam veteran uses his survival skills against a small-town police chief hunting him.", rating: "7.7 ⭐", watch: "Amazon Prime Video" },
    { title: "Race", desc: "Two half-brothers compete in a dangerous game of betrayal, insurance fraud, and murder.", rating: "6.7 ⭐", watch: "Netflix" },
    { title: "RoboCop", desc: "In a dystopic Detroit, a terminally wounded cop is returned to the police force as a powerful cyborg.", rating: "7.6 ⭐", watch: "Amazon Prime Video" },
    { title: "Brothers", desc: "Two estranged brothers with painful pasts collide in a high-stakes mixed martial arts tournament.", rating: "6.5 ⭐", watch: "Netflix" },
    { title: "Face/Off", desc: "An FBI agent undergoes facial transplant surgery to assume the identity of a mastermind, who then steals the agent's identity.", rating: "7.3 ⭐", watch: "Amazon Prime Video" },
    { title: "Kick", desc: "An adrenaline junkie who loves finding a 'kick' in everything becomes a Robin Hood-style thief.", rating: "5.6 ⭐", watch: "Disney+ Hotstar" }
  ],

  comedy: [
    { title: "Hera Pheri", desc: "Three unemployed men look for quick cash and end up involved in a chaotic kidnapper phone call mix-up.", rating: "8.1 ⭐", watch: "Amazon Prime Video" },
    { title: "Superbad", desc: "Two co-dependent high school seniors deal with separation anxiety during a wild night searching for alcohol.", rating: "7.6 ⭐", watch: "Netflix" },
    { title: "3 Idiots", desc: "Two friends search for their long-lost college roommate while recalling his unconventional lessons.", rating: "8.4 ⭐", watch: "Amazon Prime Video" },
    { title: "The Hangover", desc: "Three groomsmen wake up from a bachelor party in Las Vegas with no memory of the night and a missing groom.", rating: "7.7 ⭐", watch: "Amazon Prime Video" },
    { title: "Phir Hera Pheri", desc: "Raju, Shyam, and Baburao get scammed by a fake investment scheme and try to recover their lost money.", rating: "7.2 ⭐", watch: "Amazon Prime Video" },
    { title: "Step Brothers", desc: "Two middle-aged, spoiled men become rival stepbrothers when their single parents marry each other.", rating: "6.9 ⭐", watch: "Netflix" },
    { title: "Bhool Bhulaiyaa", desc: "An NRI and his wife stay in his ancestral mansion, ignoring warnings about an ancient vengeful ghost.", rating: "7.4 ⭐", watch: "Netflix" },
    { title: "Mean Girls", desc: "A homeschooled teenager navigates the treacherous social hierarchy of an American high school.", rating: "7.1 ⭐", watch: "Netflix" },
    { title: "Dhamaal", desc: "Four lazy friends race across India to locate a hidden treasure buried under a giant 'W' in Goa.", rating: "7.5 ⭐", watch: "Amazon Prime Video" },
    { title: "Anchorman: The Legend of Ron Burgundy", desc: "A top-rated 1970s TV newsman clashes with his new feminist female co-anchor.", rating: "7.1 ⭐", watch: "Amazon Prime Video" },
    { title: "Welcome", desc: "Two underworld dons try to marry off their innocent sister to a respectable man from a peaceful family.", rating: "7.0 ⭐", watch: "Netflix" },
    { title: "Groundhog Day", desc: "A narcissistic TV weatherman finds himself inexplicably living the same day over and over again.", rating: "8.0 ⭐", watch: "Amazon Prime Video" },
    { title: "Golmaal: Fun Unlimited", desc: "Four runaway friends take shelter in a bungalow owned by a blind couple, posing as their grandson.", rating: "7.4 ⭐", watch: "Netflix" },
    { title: "Tropic Thunder", desc: "A group of self-absorbed actors making a big-budget war movie are dropped into a real jungle combat zone.", rating: "7.1 ⭐", watch: "Amazon Prime Video" },
    { title: "Munna Bhai M.B.B.S.", desc: "A street thug pretends to be a doctor to satisfy his father's wishes, revolutionizing a medical college.", rating: "8.1 ⭐", watch: "Amazon Prime Video" },
    { title: "Shaun of the Dead", desc: "An uninspired salesman and his lazy best friend must navigate a sudden London zombie apocalypse.", rating: "7.9 ⭐", watch: "Amazon Prime Video" },
    { title: "Lage Raho Munna Bhai", desc: "A gangster starts seeing hallucinations of Mahatma Gandhi, adopting non-violent methods to win over a radio jockey.", rating: "8.0 ⭐", watch: "Amazon Prime Video" },
    { title: "Dumb and Dumber", desc: "Two incredibly dim-witted friends cross the country to return a briefcase to its owner.", rating: "7.3 ⭐", watch: "Amazon Prime Video" },
    { title: "Stree", desc: "In a small town, a malevolent female spirit abducts men at night during a festival unless written warnings protect them.", rating: "7.5 ⭐", watch: "Netflix" },
    { title: "Bridesmaids", desc: "Competition between the maid of honor and a bridesmaid threatens to ruin a mutual friend's wedding.", rating: "6.8 ⭐", watch: "Netflix" },
    { title: "Fukrey", desc: "Four college slackers seek quick money through lottery dreams, getting entangled with a tough female gangster.", rating: "7.0 ⭐", watch: "Amazon Prime Video" },
    { title: "21 Jump Street", desc: "Two youthful-looking police officers go undercover at a local high school to bust a synthetic drug ring.", rating: "7.2 ⭐", watch: "Netflix" },
    { title: "Delhi Belly", desc: "Three roommates accidentally become targets of a ruthless smuggler when a package of smuggled diamonds gets swapped.", rating: "7.5 ⭐", watch: "Netflix" },
    { title: "Ferris Bueller's Day Off", desc: "A high school wise-guy fakes an illness to spend a glorious day off in Chicago with his friends.", rating: "7.8 ⭐", watch: "Amazon Prime Video" }
  ]
};

// Function to select and render a random movie from the chosen genre
function pickMovie(genre) {
  const genreList = movieData[genre];
  
  if (!genreList || genreList.length === 0) return;

  // Play audio safely
  shuffleSound.currentTime = 0;
  shuffleSound.play().catch(() => {});

  // Pick random movie
  const randomIndex = Math.floor(Math.random() * genreList.length);
  const movie = genreList[randomIndex];

  // Render properties directly to DOM
  document.getElementById('movie-title').textContent = movie.title;
  document.getElementById('movie-desc').textContent = movie.desc;
  document.getElementById('movie-rating').textContent = movie.rating;
  document.getElementById('movie-watch').textContent = `Available on: ${movie.watch}`;
}
